version: "3"
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
  server:
    container_name: "web-messenger-server"
    build:
      context: ./server/
    volumes:
      - ./server:/usr/src/server
      - ./server/package.json:/usr/src/server/package.json
      - /usr/src/server/node_modules
    ports:
      - '5000:5000'
  client:
    container_name: "web-messenger-client"
    build:
      context: ./client/
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
    ports:
      - '80:3000'